# Generated by Django 5.2.11 on 2026-02-28 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(blank=True, max_length=100, verbose_name='代號')),
                ('clearance_level', models.IntegerField(default=1, verbose_name='權限等級')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / 現役'), ('MIA', 'MIA / 失蹤'), ('KIA', 'KIA / 陣亡'), ('RETIRED', 'Retired / 退休')], default='ACTIVE', max_length=10)),
                ('missions_completed', models.IntegerField(default=0, verbose_name='完成任務數')),
                ('confirmed_kills', models.IntegerField(default=0, verbose_name='擊殺數')),
                ('accuracy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='命中率')),
                ('bio', models.TextField(blank=True, verbose_name='特工履歷')),
                ('specialization', models.CharField(default='Survive', max_length=100, verbose_name='專長')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='agent_avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
